### ISSUE TITLE
代码文件缺失

### ISSUE THREAD

**Issue by Whhhzc** [shenxiang-vqa/LSAT#6]
你好，作者，非常感谢您在百忙之中浏览我的这个问题。我再运行您的代码时出现了报错，显示文件夹不存在
Traceback (most recent call last):
  File "/home/snnu2023304292/LSAT-main/run.py", line 148, in <module>
    __C = CfgLoader(yaml_dict['MODEL_USE']).load()
  File "/home/snnu2023304292/LSAT-main/openvqa/models/model_loader.py", line 27, in load
    return self.cfg_moudle.Cfgs()
  File "/home/snnu2023304292/LSAT-main/openvqa/models/mcan/model_cfgs.py", line 11, in __init__
    super(Cfgs, self).__init__()
  File "/home/snnu2023304292/LSAT-main/openvqa/core/base_cfgs.py", line 14, in __init__
    super(BaseCfgs, self).__init__()
  File "/home/snnu2023304292/LSAT-main/openvqa/core/path_cfgs.py", line 10, in __init__
    self.init_path()
  File "/home/snnu2023304292/LSAT-main/openvqa/core/path_cfgs.py", line 100, in init_path
    if 'result_test' not in os.listdir('./results'):
FileNotFoundError: [Errno 2] No such file or directory: './results'  
提示results这个路径不存在 我看您的代码里没有result这个文件夹 请问可以提供一下吗  非常感谢！

**Comment by shenxiang-vqa** [comment]
自己创建空的文件夹就可以，命名和代码中的保持一致。用于存放运行结果

**Comment by Whhhzc** [comment]
好的好的 非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shenxiang-vqa/LSAT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月17日(星期一) 晚上9:13
***@***.***&gt;;
抄送:&nbsp;"王海航 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [shenxiang-vqa/LSAT] 代码文件缺失 (Issue #6)





 
自己创建空的文件夹就可以，命名和代码中的保持一致。用于存放运行结果

**Comment by Whhhzc** [comment]
您好 我还有一个问题  在代码运行时报错  (LSTA) snnu2023304292@n1:~/LSAT-main$ python run.py --RUN='train' --MODEL='mcan_small' --DATASET='vqa'
Checking dataset ........
./data/vqa/feats/train2014 NOT EXIST         
vqa    数据集不存在 我看您的代码里data目录下也没有vqa这个文件夹  请问这一部分要怎么解决呢  再次感谢您回答我的问题！祝您学业有成 事事顺心！

**Comment by shenxiang-vqa** [comment]
这个你自己去下载VQA2.0数据集，然后放在对应的目录下。我文章中使用了两个数据集格式，一个是区域特征，另外一个是网格的，网格的需要自己提取特征，区域的可以直接去网上下载使用。数据集问题可以参照TRAR中的数据准备。

**Comment by Whhhzc** [comment]
好嘞 非常感谢您！ 我有一个冒昧的请求，能否添加一下您的联系方式 我是刚入门 所以对于代码还是有一些问题想要向您请教 如果可以的话 请允许我添加以下您的联系方式 非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shenxiang-vqa/LSAT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月17日(星期一) 晚上9:28
***@***.***&gt;;
抄送:&nbsp;"王海航 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [shenxiang-vqa/LSAT] 代码文件缺失 (Issue #6)





 
这个你自己去下载VQA2.0数据集，然后放在对应的目录下。我文章中使用了两个数据集格式，一个是区域特征，另外一个是网格的，网格的需要自己提取特征，区域的可以直接去网上下载使用。数据集问题可以参照TRAR中的数据准备。

**Comment by shenxiang-vqa** [comment]
sx1599181

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月17日 22:20 |
| 收件人 | shenxiang-vqa/LSAT ***@***.***> |
| 抄送人 | shenxiang-vqa ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [shenxiang-vqa/LSAT] 代码文件缺失 (Issue #6) |

好嘞 非常感谢您！ 我有一个冒昧的请求，能否添加一下您的联系方式 我是刚入门 所以对于代码还是有一些问题想要向您请教 如果可以的话 请允许我添加以下您的联系方式 非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "shenxiang-vqa/LSAT" ***@***.***&gt;;
发送时间:&nbsp;2024年6月17日(星期一) 晚上9:28
***@***.***&gt;;
抄送:&nbsp;"王海航 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [shenxiang-vqa/LSAT] 代码文件缺失 (Issue #6)






这个你自己去下载VQA2.0数据集，然后放在对应的目录下。我文章中使用了两个数据集格式，一个是区域特征，另外一个是网格的，网格的需要自己提取特征，区域的可以直接去网上下载使用。数据集问题可以参照TRAR中的数据准备。
